### ISSUE TITLE
[Feature] Typos on response body messages

### ISSUE THREAD

**Issue by alexghergh** [CNITV/SQLiggyBank#31]
The endpoints for groups, banks, and goals have small typos in their response messages.

Ex:
**{{host}}/api/banks/{{testGroupName}}/{{testBankName}}**
{
    "statusCode": 404,
    "message": "Resource not found!",
    **"details": "The piggy bank \\"testBank\\" could not be found!"**
}

SHOULD BE:
...
    "details": "The piggy bank testBank could not be found!"
...

OR

**{{host}}/api/groups/{{testGroupName}}** (when the group isn't found)
{
    "statusCode": 404,
    "message": "Resource not found!",
    **"details": "testGroupcould not be found! Try again!"**
}

SHOULD BE:
...
    **"details": "testGroup could not be found! Try again!"**
...

**Comment by StormFireFox1** [comment]
Fixed in [this commit](https://github.com/CNITV/SQLiggyBank/commit/bb4afa20e0932488683cf3d387e00c035b4d1cd2).

**Comment by alexghergh** [comment]
Please keep this issue open for possible typos that may still exist in the code.

**Comment by alexghergh** [comment]
Typo on endpoint **{{host}}/api/banks/{{testGroupName}}/testbank** when the bank doesn't exist.
I.E.:
Current:
    "details": "The piggy bank \"testbank\" could not be found!"
Expected:
    "details": "The piggy bank testbank could not be found!"

**Comment by StormFireFox1** [comment]
Well, I thought it would be much cleaner to not have a pinned issue, but eh,
your choice.

-- 
Matei-Alexandru Gardus (Storm_FireFox1)
https://stormhub.io
